ECHO = @echo
MAKE = make
API = api

help:
	$(ECHO) "mail2tat app Makefile"
	$(ECHO) "'make go-build'	Build the app, don't forget to source your custom configuration in environment variables"

go-build:
	$(MAKE) -C $(API) go-build
