ECHO = @echo
GO = go

help:
	$(ECHO) "tat2xmpp app Makefile"
	$(ECHO) "'make go-build'	Build the app, don't forget to source your custom configuration in environment variables"

go-build:
	$(GO) build
